### ISSUE TITLE
创建API接口之后会出现右斜杠'\' 

### ISSUE THREAD

**Issue by liu-frank** [kliuj/local-ajax-api#1]
1.创建一个api，例如{"code":1,"msg":2}
2.在生成文件.json文件会发现这个文件里面的detail字段，变成这种格式\ "a":1

**Comment by liu-frank** [comment]
已经帮你修复，解决方案建议在create.js的地方需要将stringValueJson.detail这个字段单独处理一下，要不然会出现jsonString的格式，在页面上显示就会出现‘\’

**Comment by kliuj** [comment]
hi  你好，已经在预览的时候处理了这种斜杠，不过在create.ejs里面为了换行格式的统一没有处理，所以文件里还是有斜杠，
